-- PostgreSQL translation of the embedded Arcade CMS schema.
-- Mechanical conversion only; no production database was changed.
-- Review enum/check semantics and installer placeholders before applying.

-- Extracted from arcade_cms/assets/includes/core.php
-- Source CMS schema/data definitions; MySQL/MariaDB syntax retained intentionally.

CREATE TABLE IF NOT EXISTS "gm_account" (
                "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "name" text NOT NULL,
                "username" varchar(250) NOT NULL,
                "password" varchar(250) NOT NULL,
                "admin" text NOT NULL DEFAULT '0',
                "email" varchar(250) NOT NULL,
                "avatar_id" integer NOT NULL,
                "xp" integer NOT NULL,
                "language" varchar(250) NOT NULL,
                "profile_theme" varchar(250) NOT NULL DEFAULT 'style-1',
                "ip" varchar(250) NOT NULL,
                "registration_date" integer NOT NULL,
                "last_logged" integer NOT NULL,
                "last_update_info" integer NOT NULL,
                "active" text NOT NULL,
                PRIMARY KEY ("id") 
            );

CREATE TABLE IF NOT EXISTS "gm_users" (
                "user_id" integer NOT NULL,
                "gender" text NOT NULL DEFAULT '1',
                "about" text NOT NULL DEFAULT '', UNIQUE ("user_id")
            );

CREATE TABLE IF NOT EXISTS "gm_ads" (
                "id" integer NOT NULL,
                "728x90" varchar(700) NOT NULL,
                "300x250" varchar(700) NOT NULL,
                "600x300" varchar(700) NOT NULL,
                "728x90_main" varchar(700) NOT NULL,
                "300x250_main" varchar(700) NOT NULL,
                "ads_video" varchar(700) NOT NULL,
                PRIMARY KEY ("id")
            );

INSERT INTO "gm_ads" ("id", "728x90", "300x250", "600x300", "728x90_main", "300x250_main", "ads_video") VALUES (1, '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS "gm_categories" (
                "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "category_pilot" varchar(250) NOT NULL,
                "name" text NOT NULL,
                "image" varchar(400) NOT NULL,
                "footer_description" TEXT NULL DEFAULT '',
                PRIMARY KEY ("id")
            );

INSERT INTO "gm_categories" ("id", "category_pilot", "name", "image") VALUES
(1, 'action-games', 'Action Games', '/cat/action-games.jpg'),
(2, 'racing-games', 'Racing Games', '/cat/racing-games.png'),
(3, 'shooting-games', 'Shooting Games', '/cat/shooting-games.jpg'),
(4, 'arcade-games', 'Arcade Games', '/cat/arcade-games.jpg'),
(5, 'puzzle-games', 'Puzzle Games', '/cat/puzzle-games.jpg'),
(6, 'strategy-games', 'Strategy Games', '/cat/strategy-games.png'),
(7, 'multiplayer-games', 'Multiplayer Games', '/cat/multiplayer-games.jpg'),
(8, 'sports-games', 'Sports Games', '/cat/sports-games.png'),
(9, 'fighting-games', 'Fighting Games', '/cat/fighting-games.png');

CREATE TABLE IF NOT EXISTS "gm_games" (
                "game_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "catalog_id" varchar(250) NOT NULL,
                "game_name" varchar(250) NOT NULL,
                "name" varchar(250) NOT NULL,
                "image" varchar(500) NOT NULL,
                "import" text NOT NULL DEFAULT '0',
                "category" integer NOT NULL,
                "plays" integer NOT NULL DEFAULT 0,
                "rating" text NOT NULL DEFAULT '0',
                "description" varchar(15000) NOT NULL,
                "instructions" varchar(600) NOT NULL,
                "file" varchar(500) NOT NULL,
                "game_type" varchar(250) NOT NULL,
                "w" integer NOT NULL,
                "h" integer NOT NULL,
                "date_added" integer NOT NULL,
                "published" text NOT NULL,
                "featured" text NOT NULL DEFAULT '0',
                "mobile" integer NOT NULL DEFAULT 0,
                "featured_sorting" varchar(255) NOT NULL DEFAULT '',
                "field_1" varchar(500) NOT NULL DEFAULT '',
                "field_2" varchar(500) NOT NULL DEFAULT '',
                "field_3" varchar(500) NOT NULL DEFAULT '',
                "field_4" varchar(500) NOT NULL DEFAULT '',
                "field_5" varchar(500) NOT NULL DEFAULT '',
                "field_6" varchar(500) NOT NULL DEFAULT '',
                "field_7" varchar(500) NOT NULL DEFAULT '',
                "field_8" varchar(500) NOT NULL DEFAULT '',
                "field_9" varchar(500) NOT NULL DEFAULT '',
                "field_10" varchar(500) NOT NULL DEFAULT '',
                "tags_ids" jsonb NULL DEFAULT NULL,
                "video_url" VARCHAR(100) NULL DEFAULT NULL,
                "like_count" integer NOT NULL DEFAULT 0,
                "dislike_count" integer NOT NULL DEFAULT 0,
                "favorite_count" integer NOT NULL DEFAULT 0,
                PRIMARY KEY ("game_id")
            );

CREATE TABLE IF NOT EXISTS "gm_media" (
                "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "name" varchar(250) NOT NULL,
                "extension" varchar(250) NOT NULL DEFAULT 'none',
                "type" varchar(250) NOT NULL DEFAULT 'none',
                "url" varchar(250) NOT NULL,
                PRIMARY KEY ("id")
            );

CREATE TABLE IF NOT EXISTS "gm_setting" (
                "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "site_name" varchar(500) NOT NULL,
                "site_url" varchar(500) NOT NULL,
                "site_theme" varchar(500) NOT NULL,
                "site_description" varchar(500) NOT NULL DEFAULT 'Best Free Online Games',
                "site_keywords" varchar(500) NOT NULL DEFAULT 'games, online, arcade, html5, gamemonetize',
                "ads_status" text NOT NULL DEFAULT '0',
                "ad_time" integer NOT NULL DEFAULT '10',
                "language" varchar(250) NOT NULL,
                "featured_game_limit" integer NOT NULL,
                "mp_game_limit" integer NOT NULL,
                "xp_play" integer NOT NULL,
                "xp_report" integer NOT NULL,
                "xp_register" integer NOT NULL,
                "plays" integer NOT NULL,
                "custom_game_feed_url" VARCHAR(1000) DEFAULT NULL,
                "settings_1" varchar(500) NOT NULL DEFAULT '',
                "settings_2" varchar(500) NOT NULL DEFAULT '',
                "settings_3" varchar(500) NOT NULL DEFAULT '',
                "settings_4" varchar(500) NOT NULL DEFAULT '',
                "settings_5" varchar(500) NOT NULL DEFAULT '',
                "settings_6" varchar(500) NOT NULL DEFAULT '',
                "settings_7" varchar(500) NOT NULL DEFAULT '',
                "settings_8" varchar(500) NOT NULL DEFAULT '',
                "settings_9" varchar(500) NOT NULL DEFAULT '',
                "settings_10" varchar(500) NOT NULL DEFAULT '',
                PRIMARY KEY ("id")
            );

INSERT INTO "gm_setting" (
    "id","site_name","site_url","site_theme","site_description","site_keywords",
    "ads_status","ad_time","language","featured_game_limit","mp_game_limit",
    "xp_play","xp_report","xp_register","plays","custom_game_feed_url",
    "settings_1","settings_2","settings_3","settings_4","settings_5",
    "settings_6","settings_7","settings_8","settings_9","settings_10"
  ) VALUES (
    1,
    'Poki Crazy Games',
    'https://pokicrazygames.vercel.app',
    'kizi',
    'Best Free Online Games',
    'games, online, arcade, html5, free games',
    '0',10,'english',8,12,50,100,10,0,
    'https://gamemonetize.com/feed.php?format=0&num=60',
    '','','','','','','','','',''
  );

CREATE TABLE IF NOT EXISTS "gm_theme" (
                "theme_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "theme_class" varchar(250) NOT NULL,
                PRIMARY KEY ("theme_id"), UNIQUE ("theme_class")
            );

INSERT INTO "gm_theme" ("theme_id", "theme_class") VALUES (1, 'style-1'), (2, 'style-1-image'), (3, 'style-2'), (4, 'style-2-image'), (5, 'style-3'), (6, 'style-3-image'), (7, 'style-4'), (8, 'style-5'), (9, 'style-6'), (10, 'style-7');

CREATE TABLE IF NOT EXISTS "gm_tags" (
        "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "url" varchar(100) NOT NULL,
        "name" varchar(100) NOT NULL,
        "footer_description" text DEFAULT '',
        PRIMARY KEY ("id"), UNIQUE ("url")
       );

CREATE TABLE IF NOT EXISTS "gm_footer_description" (
        "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "page_name" varchar(100) NOT NULL,
        "page_url" varchar(100) NOT NULL,
        "description" text NOT NULL,
        "has_content" text NOT NULL DEFAULT '0',
        "content_value" text DEFAULT '',
        PRIMARY KEY ("id")
      );

INSERT INTO "gm_footer_description" ("page_name", "page_url", "description", "has_content", "content_value") VALUES
    ('home', '/', '', '0', ''),
    ('new games', '/new-games', '', '0', ''),
    ('best games', '/best-games', '', '0', ''),
    ('featured games', '/featured-games', '', '0', ''),
    ('played games', '/played-games', '', '0', ''),
    ('about', '/about', '', '0', ''),
    ('contact', '/contact', '', '0', ''),
    ('privacy', '/privacy', '', '0', ''),
    ('terms', '/terms', '', '0', ''),
    ('blogs', '/blogs', '', '0', ''),
    ('categories', '/categories', '', '0', ''),
    ('search', '/search', '', '0', '');

CREATE TABLE IF NOT EXISTS "gm_blogs" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(100) NOT NULL,
    "url" varchar(100) NOT NULL,
    "image_url" varchar(200) DEFAULT NULL,
    "post" text DEFAULT NULL,
    "date_created" date DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "gm_chatgpt" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "api_key" varchar(200) DEFAULT NULL,
    "template_game" text DEFAULT NULL,
    "template_category" text DEFAULT NULL,
    "template_tags" text DEFAULT NULL,
    "template_footer" text DEFAULT NULL,
    "random_words_before_tags" varchar(1000) DEFAULT NULL,
    "random_words_after_tags" varchar(1000) DEFAULT NULL,
    "chatgpt_model" varchar(100) NOT NULL DEFAULT 'gpt-3.5-turbo',
    "maximum_words" integer NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

INSERT INTO "gm_chatgpt" (
    "id","api_key","template_game","template_category","template_tags","template_footer",
    "random_words_before_tags","random_words_after_tags","chatgpt_model","maximum_words"
  ) VALUES (1, NULL, '', '', '', '', '', '', 'gpt-4o-mini', 0);

CREATE TABLE IF NOT EXISTS "gm_links" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "url" varchar(100) NOT NULL,
    "is_active" smallint NOT NULL DEFAULT 0,
    "is_chatgpt" smallint NOT NULL,
    "language_list" varchar(100) DEFAULT 'de,es,fr,it',
    "rewrite_method" varchar(100) DEFAULT NULL,
    "google_translate_language" varchar(100) DEFAULT NULL,
    "last_id" integer DEFAULT NULL,
    "autopost_fail_count" integer NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

INSERT INTO "gm_links" ("id", "name", "url", "is_active", "is_chatgpt", "language_list", "rewrite_method", "google_translate_language", "last_id", "autopost_fail_count") VALUES
(1, 'autopost', 'eJqmslXERPi0dpA649Qky2ujN8WZCxHbotY1wfv5', 0, 0, 'de,es,fr,it', 'chatgpt', 'es', NULL, 0),
(3, 'autopost_old_games', 'HLdsx7baSp2WlByVRf61CIZwmG9KOvA5toDceYNU', 0, 0, 'de,es,fr,it', NULL, NULL, 119, 0),
(4, 'autopost_tags', 'ozCgqUuKfRYkILGHZjE0hAyevMQlN8P13O62rVsS', 0, 0, 'de,es,fr,it', NULL, NULL, 387, 0);

CREATE TABLE IF NOT EXISTS "gm_sliders" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar(100) NOT NULL,
    "category_tags_id" integer NOT NULL,
    "ordering" integer NOT NULL,
    PRIMARY KEY ("id")
);

INSERT INTO "gm_sliders" ("id", "type", "category_tags_id", "ordering") VALUES
(3, 'best', 0, 40),
(18, 'category', 2, 80),
(24, 'category', 4, 70);

CREATE TABLE IF NOT EXISTS "gm_sidebar" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL,
    "type" varchar(100) NOT NULL,
    "category_tags_id" integer DEFAULT NULL,
    "custom_link" varchar(100) DEFAULT NULL,
    "icon" varchar(100) DEFAULT NULL,
    "ordering" varchar(3) NOT NULL DEFAULT '999',
    PRIMARY KEY ("id")
);

INSERT INTO "gm_sidebar" ("id", "name", "type", "category_tags_id", "custom_link", "icon", "ordering") VALUES
(2, 'New Games', 'new', 0, '', 'new_releases', '20'),
(3, 'Popular Games', 'best', 0, '', 'fa-solid fa-ranking-star', '30'),
(4, 'Played Games', 'separator', 0, '', '', '36'),
(5, 'Featured', 'featured', 0, '', 'auto_graph', '35'),
(6, 'Separator', 'separator', 0, '', '', '70'),
(7, 'Racing', 'category', 2, '', 'fa-solid fa-flag-checkered', '40'),
(8, 'Action', 'category', 1, '', 'local_fire_department', '43'),
(9, 'Dress Up', 'tags', 3, '', 'fa-solid fa-person-pregnant', '47');

ALTER TABLE "gm_setting"
    ADD COLUMN IF NOT EXISTS "recaptcha_site_key" VARCHAR(100) NULL, 
    ADD COLUMN IF NOT EXISTS "recaptcha_secret_key" VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS "is_sidebar_enabled" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "gm_games" 
    ADD COLUMN IF NOT EXISTS "is_last_rewrite" smallint NOT NULL DEFAULT '0';

ALTER TABLE "gm_tags" 
    ADD COLUMN IF NOT EXISTS "is_last_rewrite" smallint NOT NULL DEFAULT '0',
    ADD COLUMN IF NOT EXISTS "is_rewrited" smallint NOT NULL DEFAULT '0';


CREATE TABLE IF NOT EXISTS "gm_game_actions" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "game_id" integer NOT NULL,
    "visitor_token" varchar(100) NOT NULL,
    "ip_address" varchar(64) DEFAULT NULL,
    "action_type" varchar(20) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("game_id", "visitor_token", "action_type")
);

CREATE INDEX IF NOT EXISTS "gm_game_actions_game_id_idx"
    ON "gm_game_actions" ("game_id");

CREATE TABLE IF NOT EXISTS "gm_reports" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "game_id" integer NOT NULL,
    "game_name" varchar(500) NOT NULL,
    "user_email" varchar(320) NOT NULL,
    "report_type" varchar(100) NOT NULL,
    "subject" varchar(500) NOT NULL,
    "message" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);


SELECT setval(pg_get_serial_sequence('"gm_ads"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_ads"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_categories"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_categories"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_setting"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_setting"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_theme"', 'theme_id'), GREATEST(COALESCE((SELECT MAX("theme_id") FROM "gm_theme"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_footer_description"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_footer_description"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_chatgpt"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_chatgpt"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_links"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_links"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_sliders"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_sliders"), 1), 1), true);
SELECT setval(pg_get_serial_sequence('"gm_sidebar"', 'id'), GREATEST(COALESCE((SELECT MAX("id") FROM "gm_sidebar"), 1), 1), true);
