FROM dunglas/frankenphp:1-php8.3-bookworm

RUN install-php-extensions mysqli pdo_pgsql pgsql curl mbstring zip gd

WORKDIR /app
COPY . /app
COPY Caddyfile.vercel /etc/caddy/Caddyfile

ENV SERVER_NAME=:80

CMD ["frankenphp","run","--config","/etc/caddy/Caddyfile","--adapter","caddyfile"]
